language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: VQhK1nEMrjK1Pap221yR1smmyYpeI3iGqvva9Ap+vNkr7AQfYIYwD5T99tvAh3VoOydBJZZ63cd+aV97QhfyFgzV9hWpHWwSxPghiv8WALG672zEyQwIg5SrD2n5h2xTYcUPU0mm5wuZeTRu9UywBgiDSRzLMTLbTxQJfjh3TN8ThCe2pwMbn656mYGCQJre+GJob9QxlMtPaoHzHZOJ9+85WLlv8MOY4BWLUawf6mlU87XAufgrdjtjzwhPT6tIUdFb/vj6giLT+ETAOzAF4HOtbNJsVaDHej5RnYyBGE2tu1V4s8ZmTtIKbDerSK6BYa7DCd2Ig4uJSHVDxqQBAz0i547vIHAPfwlrPU1AcR2nUgxQ3HpPrysEQoEvivqkUSPHOXrUYZXuHUBKY6jT8ZMDPtfcm0bQTyBZxUp7uwETH3zrH+JrH1e7PV7shMEL5gkiiq/iDvRkEx2ZMaHCfVd01Yj9yJ3Y+Ju8hiYrNWNBi4qdVCwSevqnE2/+NJykYcuVAVQDVFXz+WKyJQ/XaHzZ1vxm3bgso7iEXYN9BJH9BM02pbH5woLKYMM1Vw9EwLywi18ARCGyt7sNYg0U9tHkT8nqonqDYLHWIgs3baSMEy6X3gE/DgosEIu5Vg8JG4UTChC9vJviP90igXBW1NECYFW20sziK+zf4XXuSHE=
